### ISSUE TITLE
Credentials.CLOUDANT_URL_CREATE

### ISSUE THREAD

**Issue by vperrinfr** [IBM/ar-resume-with-visual-recognition#15]
In the code, you are calling "Credentials.CLOUDANT_URL_CREATE" in CloudRESTCall which is not referred in Credentials file. 

Can we use "Credentials.CLOUDANT"

**Comment by sanjeevghimire** [comment]
Looking into it

**Comment by sanjeevghimire** [comment]
@vperrinfr I have added CLOUDANT_GET to get documents and CLOUDANT_CREATE to create documents as URL names.
Please checkout the pull request: https://github.com/IBM/ar-resume-with-visual-recognition/pull/16
