### ISSUE TITLE
Sample image zips have been removed

### ISSUE THREAD

**Issue by nickmazzi** [IBM/ar-resume-with-visual-recognition#31]
The sample image data for building the model has been removed from the repository. The readme still references these packages in step 3:

```
When the app loads, the app will create 3 classifiers for each of the zip files ResumeAR/sanjeev.zip, ResumeAR/steve.zip and ResumeAR/scott.zip.
```

If users are no longer supposed to use these packages, we should remove the links to them from the readme and provide somewhere else to get sample data from.

**Comment by sanjeevghimire** [comment]
@nickmazzi looking into it. We are not using it as we are using the ML model. Let me update the readme with proper instructions.

**Comment by stevemar** [comment]
We checked in three Core ML models instead in https://github.com/IBM/ar-resume-with-visual-recognition/commit/dad9e52e3cacc67598555b4ba66795aec5a48056
