### ISSUE TITLE
Upgrade Watson SDK to 0.37.0

### ISSUE THREAD

**Issue by christiancompton** [IBM/ar-resume-with-visual-recognition#34]
A semver issue in a dependecy has broken all projects using the Watson SDK before release 0.36.0.  Please upgrade to version 0.37.0 to ensure dependency resolution will work.

**Comment by christiancompton** [comment]
I see versions are not locked in the Cartfile, so maybe this kit is not impacted.

**Comment by sanjeevghimire** [comment]
@christiancompton is the interface changed in Watson SDK for viz rec? if yes we need to change if not just version change should not affect it.

I will test it though.

**Comment by dolph** [comment]
It sounds like the dependency should have a release artifact deleted and be re-released.

**Comment by christiancompton** [comment]
@dolph I concur, but no dice.  https://github.com/daltoniam/Starscream/issues/587

**Comment by christiancompton** [comment]
@sanjeevghimire There are no interface changes that I am aware of.

**Comment by stevemar** [comment]
will be solved in #36
