### ISSUE TITLE
Build failing with errors

### ISSUE THREAD

**Issue by RiyaMRoy04** [IBM/ar-resume-with-visual-recognition#36]
Build is failing and hitting with below attached error. Please help in resolving the same!
<img width="278" alt="screen shot 2018-12-11 at 9 37 37 pm" src="https://user-images.githubusercontent.com/11567379/49813666-efc9dc80-fd8d-11e8-82a5-c73bc8880af2.png">

**Comment by stevemar** [comment]
This is related to a few backwards incompatible changes to the watson SDK. 

specifically the `listClassifiers` and `classifyLocal` methods have changed to have two results (`response` and `error`):

```
        visualRecognition.listClassifiers { response, error in
```

https://github.com/watson-developer-cloud/swift-sdk/blob/add0c54377232f58430fa5e4e43ea0ad23fc4c43/Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift#L97

**Comment by markstur** [comment]
@RiyaMRoy04 I pushed build fixes, but I don't have a fully working test environment.  Can you test this?

**Comment by RiyaMRoy04** [comment]
@stevemart Thank you for the update!
@markstur Sure, will test and update you!
