### ISSUE TITLE
app crashes after finding face

### ISSUE THREAD

**Issue by stevemar** [IBM/ar-resume-with-visual-recognition#44]
See https://github.com/IBM/ar-resume-with-visual-recognition/pull/43 for details.

**Comment by christiancompton** [comment]
To clarify - the app does load and work properly for maybe 30 seconds after discovering a face (and sometimes rendering the AR data).  Then it crashes with a Seg Fault error.  I suspect something with the threading or garbage collection must be addressed.

This is on iPhone X.

**Comment by sanjeevghimire** [comment]
Looking into recreating the issue

**Comment by christiancompton** [comment]
I tested the changes in #47 on my iPhone X - the issue has been fixed.
